---
title: "data-collection"
output: html_document
date: "2023-02-06"
---
#libraries
```{r}
library(httr)
library(tidyverse)
library(jsonlite)
library(stringr)
library(nbastatR)
library(xml2)
library(rvest)
library(curl)
library(devtools)
library(ncaahoopR)
library(extrafont)
library(teamcolors)
library(lubridate)
```

#base setup (player/season selector)
```{r}
#set working directory
setwd("/Users/danielbrockett/Desktop/personalProject")

#nba.com player ID retrieval
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

#nba player data
assign_nba_players()
dfNBAdict <- df_dict_nba_players
rm(df_dict_nba_players)

keep <- c(1:7)
dfNBAdict <- dfNBAdict[,keep]

#nba Player ID
pidNBA <- dfNBAdict %>%
  filter(str_detect(namePlayer, "LeBron")) %>%
  select(idPlayer)

#season inputs
sznStartYear <- c(2003:2022)
sznEndYear <- sznStartYear + 1
years <- tibble(sznStartYear, sznEndYear)

#create season description
years <- years %>%
  mutate(sznYear = paste0(sznStartYear,"-",str_sub(sznEndYear, -2, -1), sep =""))

#bbRef player info
bbref <- bref_players_stats(sznEndYear[1], tables = "totals")
Sys.sleep(9)
rm(dataBREFPlayerTotals)

#clean cols
keep2 <- c(1:10)
bbref <- bbref[,keep2]

#bbRef player id
bbrefPID <- bbref %>%
  filter(str_detect(namePlayer, "LeBron") & yearSeason == sznEndYear[1]) %>%
  select(slugPlayerBREF)

#rename columns
colnames(bbrefPID) <- c("playerSlug")
```

#scrape functions
```{r}
#NBA.com Scrape function
#####
#nba.com headers
headers = c(`Connection` = 'keep-alive',
            `Accept` = 'application/json, text/plain, */*',
            `x-nba-stats-token` = 'true',
            `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36',
            `x-nba-stats-origin` = 'stats',
            `Sec-Fetch-Site` = 'same-site',
            `Sec-Fetch-Mode` = 'cors',
            `Referer` = 'https://www.nba.com/',
            `Accept-Encoding` = 'gzip, deflate, br',
            `Accept-Language` = 'en-US,en;q=0.9')

#nba.com shot location scrape function
shotChartScrape <- function(season, playerIDNumber){
  url <- paste0("https://stats.nba.com/stats/shotchartdetail?AheadBehind=&CFID=33&CFPARAMS=",season,"&ClutchTime=&Conference=&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&Division=&EndPeriod=10&EndRange=28800&GROUP_ID=&GameEventID=&GameID=&GameSegment=&GroupID=&GroupMode=&GroupQuantity=5&LastNGames=0&LeagueID=00&Location=&Month=0&OnOff=&OppPlayerID=&OpponentTeamID=0&Outcome=&PORound=0&Period=0&PlayerID=",playerIDNumber,"&PlayerID1=&PlayerID2=&PlayerID3=&PlayerID4=&PlayerID5=&PlayerPosition=&PointDiff=&Position=&RangeType=0&RookieYear=&Season=",season,"&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StartPeriod=1&StartRange=0&StarterBench=&TeamID=0&VsConference=&VsDivision=&VsPlayerID1=&VsPlayerID2=&VsPlayerID3=&VsPlayerID4=&VsPlayerID5=&VsTeamID=", sep = "")
  
  res <- GET(url = url, add_headers(.headers=headers))
  
  json_resp <- fromJSON(content(res, "text"))
  
  frame <- data.frame(json_resp$resultSets$rowSet[1])
  colnames(frame) <- json_resp[["resultSets"]][["headers"]][[1]]
  
  Sys.sleep(3)
  
  frame <- frame %>%
    mutate(GAME_ID = as.numeric(GAME_ID),
           GAME_EVENT_ID = as.numeric(GAME_EVENT_ID),
           PLAYER_ID = as.numeric(PLAYER_ID),
           TEAM_ID = as.numeric(TEAM_ID),
           PERIOD = as.numeric(PERIOD),
           MINUTES_REMAINING = as.numeric(MINUTES_REMAINING),
           SECONDS_REMAINING = as.numeric(SECONDS_REMAINING),
           SHOT_DISTANCE = as.numeric(SHOT_DISTANCE),
           LOC_X = as.numeric(LOC_X),
           LOC_Y = as.numeric(LOC_Y),
           SHOT_ATTEMPTED_FLAG = as.numeric(SHOT_ATTEMPTED_FLAG),
           SHOT_MADE_FLAG = as.numeric(SHOT_MADE_FLAG),
           GAME_YEAR = as.numeric(substr(GAME_DATE, 1, 4)),
           GAME_MONTH = as.numeric(substr(GAME_DATE, 5, 6)),
           GAME_DAY = as.numeric(substr(GAME_DATE, 7, 8)))
  
  return(frame)
  }
#####

#bbRef Scrape function
#####
scrapePlayerGames <- function(playerSlug, season){
  finitial <- substring(playerSlug, 1, 1)
  url <- paste0("https://www.basketball-reference.com/players/",finitial,"/",playerSlug,"/gamelog/",season, sep="")
 
  webpage <- read_html(url)
  games <- webpage %>%
    html_table(fill=TRUE) %>% .[[8]]
  
  Sys.sleep(3)
  
  colnames(games) <- c("rk", "gameNumber", "date", "age", "tm", "vsAT", "opponent", "mov", "gs", "mp", "fgm", "fga", "fgpct", "fg3m", "fg3a", "fg3pct", "ftm", "fta", "ftpct", "orb", "drb", "trb", "ast", "stl", 'blk', "tov", "pf", "pts", "gameScore", "plusMinus")
  
  games$homeGame <- as.integer(ifelse(games$vsAT == "", 1, 0))
  games$awayGame <- as.integer(ifelse(games$vsAT == "@", 1, 0 ))
  games$playerSlug <- playerSlug
  games$season <- as.integer(season)
  
  games$rk <- as.integer(games$rk)
  games$gameNumber <- as.integer(games$gameNumber)
  games$age <- as.integer(games$age)
  games$gs <- as.integer(games$gs)
  games$fgm <- as.integer(games$fgm)
  games$fga <- as.integer(games$fga)
  games$fg3m <- as.integer(games$fg3m)
  games$fg3a <- as.integer(games$fg3a)
  games$ftm <- as.integer(games$ftm)
  games$fta <- as.integer(games$fta)
  games$orb <- as.integer(games$orb)
  games$drb <- as.integer(games$drb)
  games$trb <- as.integer(games$trb)
  games$ast <- as.integer(games$ast)
  games$stl <- as.integer(games$stl)
  games$blk <- as.integer(games$blk)
  games$tov <- as.integer(games$tov)
  games$pf <- as.integer(games$pf)
  games$pts <- as.integer(games$pts)
  games$plusMinus <- as.integer(games$plusMinus)
  games$homeGame <- as.integer(games$homeGame)
  games$awayGame <- as.integer(games$awayGame)
  games$season <- as.integer(games$season)
  
  games$fgpct <- as.numeric(games$fgpct)
  games$fg3pct <- as.numeric(games$fg3pct)
  games$ftpct <- as.numeric(games$ftpct)
  games$gameScore <- as.numeric(games$gameScore)

  games$date <- as.character(games$date)
  games$tm <- as.character(games$tm)
  games$vsAT <- as.character(games$vsAT)
  games$opponent <- as.character(games$opponent)
  games$mov <- as.character(games$mov)
  games$mp <- as.character(games$mp)
  
  games <- games %>%
    filter(!is.na(gameNumber))
  
  games <- subset(games, select = -c(age) )
  return(games)
}
#####
```

#data collection
```{r}
#nba.com scrape (Field Goal Shot Locations)
gameEvents <- tibble()

#for loop to collect data (NBA.com)
for (i in 1:nrow(years)){
  events <- shotChartScrape(years[i,]$sznYear, pidNBA$idPlayer)
  
  gameEvents <- events %>% bind_rows(gameEvents)
  
  Sys.sleep(7)
}

#bbRef scrape (Box Scores)
gameLogs <- tibble()

#for loop to collect data (bbRef)
for (i in 1:nrow(years)){
  logs <- scrapePlayerGames(bbrefPID$playerSlug, years[i,]$sznEndYear)
  
  gameLogs <- logs %>% bind_rows(gameLogs)
  
  Sys.sleep(5)
}

#FGM check
gameEvents %>%
  group_by(PLAYER_ID) %>%
  summarise(shotsMade = sum(SHOT_MADE_FLAG))
```

#save data
```{r}
#save data (bbRef)
write_csv(gameLogs, "LeBronCareerGameLogs.csv")

#save data (NBA.com)
write_csv(gameEvents, "LeBronCareerFGA.csv")
```

#load data
```{r}
#free throws
gameLogs <- read_csv("LeBronCareerGameLogs.csv")

#field goals
gameEvents <- read_csv("LeBronCareerFGA.csv")
```