---
title: "shot-charts"
output: html_document
date: "2023-02-06"
---
#load cleaned data
```{r}
cShots <- read_csv("LeBronCareerShots.csv")
```

#NBA court dimensions
```{r}
#circle function
circle_points <- function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

#nba court dimensions
width <- 50
height <- 94
key_height <- 19
inner_key_width <- 12
outer_key_width <- 16
backboard_width <- 6
backboard_offset <- 4
neck_length <- 0.5
hoop_radius <- 0.75
hoop_center_y <- backboard_offset + neck_length + hoop_radius
three_point_radius <- 23.75
three_point_side_radius <- 22
three_point_side_height <- 14
inner_tip_off_radius <- 2
outer_tip_off_radius <- 6
```

#court themes
```{r}
#court themes
court_themes <- list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20")
)
```

#court graphing function
```{r}
#court creation function
plot_court <- function(court_theme) {
  
  court_points <- tibble(x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
                             y = c(height, 0, 0, height, height),
                             desc = "perimeter")
  
  court_points <- bind_rows(court_points, tibble(x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
                                                 y = c(0, key_height, key_height, 0),
                                                 desc = "outer_key"))
  
  court_points <- bind_rows(court_points , tibble(x = c(-backboard_width / 2, backboard_width / 2),
                                                  y = c(backboard_offset, backboard_offset),
                                                  desc = "backboard"))
  
  court_points <- bind_rows(court_points , tibble(x = c(0, 0),
                                                  y = c(backboard_offset, backboard_offset + neck_length),
                                                  desc = "neck"))
  
  foul_circle <- circle_points(center = c(0, key_height),
                               radius = inner_key_width / 2)
  
  foul_circle_top <- filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom <- filter(foul_circle, y < key_height) %>%
    mutate(angle = atan((y - key_height) / x) * 180 / pi,
           angle_group = floor((angle - 5.625) / 11.25),
           desc = paste0("foul_circle_bottom_", angle_group)) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop <- circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted <- circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle <- circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line <- tibble(x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
                            y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
                            desc = "three_point_line")
  
  courtLayout <- bind_rows(court_points,
                            foul_circle_top,
                            foul_circle_bottom,
                            hoop,
                            restricted,
                            three_point_line)
  courtflip <- courtLayout
  courtflip$y <- (-courtLayout$y) + 94

  innerTipOffCircle <- circle_points(center = c(0, height/2), radius = inner_tip_off_radius) %>%
    mutate(desc = "innerTipOffCircle")
  outerTipOffCircle <- circle_points(center = c(0, height/2), radius = outer_tip_off_radius) %>%
    mutate(desc = "outerTipOffCircle")
  
  halfcourt_line <- tibble(x = c(width / 2, -width / 2),
                             y = c(height / 2, height / 2),
                             desc = "halfcourtLine")
  halfcourtLayout <- rbind(innerTipOffCircle,
                           outerTipOffCircle,
                           halfcourt_line)

#plotting court
  ggplot() +
    geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) +
    geom_path(data = courtflip,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) + 
    geom_path(data = halfcourtLayout,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) +
    coord_fixed(ylim = c(0, 94), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(text = element_text(color = court_theme$text),
          plot.background = element_rect(fill = 'gray20', color = 'gray20'),
          panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.text = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
          legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
          legend.position = "bottom",
          legend.key = element_blank(),
          legend.text = element_text(size = rel(1.0)))
  }
```

#totals
```{r}
cTotals <- cShots %>%
  group_by(player_id) %>%
  summarise(makes = sum(shotMake),
            attempts = sum(shotAttempt),
            points = sum(pointsScored),
            shotPCT = (makes/attempts)*100)
```

#intial plot
```{r}
#check court plot
plot_court(court_themes$light)
```

#career shots
```{r}
cShots$shotMake <- as.factor(cShots$shotMake)
cShots$shotAttempt <- as.factor(cShots$shotAttempt)

plot_court(court_themes$light) + 
  geom_point(data = cShots, 
             aes(x = loc_x, y = loc_y, color = shotMake, fill = shotMake), shape = 21, alpha = 0.6) +
  scale_color_manual(values = c("green4","red3"),
                     aesthetics = "color", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"),
                    aesthetics = "fill", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  ggtitle("LeBron James Career Shot Chart", subtitle = paste0("Career Points:"," ",cTotals$points[1], sep = "")) +
  labs(fill = "Shot Result",
       color = "Shot Result",
       caption = "*As of 2/6/23") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, color = nbaColors$primary[14], size = 22),
        plot.subtitle = element_text(hjust = 0.5, color = nbaColors$primary[14]),
        legend.title = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.text = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.background = element_rect(fill = "floralwhite"),
        legend.key.height= unit(2, 'cm'),
        plot.caption = element_text(color = nbaColors$primary[14]),
        strip.text = element_text(color = "floralwhite")) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc)) +
  geom_path(data = courtflip,
            aes(x = x, y = y, group = desc)) +
  geom_path(data = halfcourtLayout,
            aes(x = x, y = y, group = desc))

ggsave("lbjCareerShots.pdf")
```

#career shots by season
```{r}
css <- cShots %>%
  mutate(sznStart = ifelse(game_month >= 10, game_year, ifelse(game_month<=9, game_year - 1, game_year)),
         sznEnd = sznStart + 1,
         szn = paste0(sznStart,"-",substr(sznEnd, 3, 4), sep = ""),
         mabb = month.abb[game_month])

plot_court(court_themes$light) + 
  geom_point(data = css, 
             aes(x = loc_x, y = loc_y, color = shotMake, fill = shotMake), shape = 21, alpha = 0.6) +
  scale_color_manual(values = c("green4","red3"),
                     aesthetics = "color", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"),
                    aesthetics = "fill", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  ggtitle("LeBron James Career Shot Chart by Season", subtitle = paste0("Career Points:"," ",cTotals$points[1], sep = "")) +
  labs(fill = "Shot Result",
       color = "Shot Result",
       caption = "*As of 2/6/23") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, color = nbaColors$primary[14], size = 22),
        plot.subtitle = element_text(hjust = 0.5, color = nbaColors$primary[14]),
        plot.caption = element_text(color = nbaColors$primary[14]),
        legend.title = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.text = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.background = element_rect(fill = "floralwhite"),
        legend.key.height= unit(2, 'cm'),
        strip.text = element_text(color = "white")) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc)) +
  geom_path(data = courtflip,
            aes(x = x, y = y, group = desc)) +
  geom_path(data = halfcourtLayout,
            aes(x = x, y = y, group = desc)) +
  facet_wrap(~szn, nrow = 3)

ggsave("lbjCareerShots-szn.pdf")

```

#shots by opponent
```{r}
plot_court(court_themes$light) + 
  geom_point(data = css, 
             aes(x = loc_x, y = loc_y, color = shotMake, fill = shotMake), shape = 21, alpha = 0.6) +
  scale_color_manual(values = c("green4","red3"),
                     aesthetics = "color", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"),
                    aesthetics = "fill", breaks=c("1", "0"), labels=c("Made", "Missed")) +
  ggtitle("LeBron James Career Shot Chart by Opponent", subtitle = paste0("Career Points:"," ",cTotals$points[1], sep = "")) +
  labs(fill = "Shot Result",
       color = "Shot Result",
       caption = "*As of 2/6/23") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, color = nbaColors$primary[14], size = 22),
        plot.subtitle = element_text(hjust = 0.5, color = nbaColors$primary[14]),
        plot.caption = element_text(color = nbaColors$primary[14]),
        legend.title = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.text = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.background = element_rect(fill = "floralwhite"),
        legend.key.height= unit(2, 'cm'),
        strip.text = element_text(color = "white")) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc)) +
  geom_path(data = courtflip,
            aes(x = x, y = y, group = desc)) +
  geom_path(data = halfcourtLayout,
            aes(x = x, y = y, group = desc)) +
  facet_wrap(~oppAbb, nrow = 3)

ggsave("lbjCareerShots-opponent.pdf")

```

#career makes
```{r}
makes <- cShots %>%
  filter(shotMake == 1)

plot_court(court_themes$light) + 
  geom_point(data = makes, 
             aes(x = loc_x, y = loc_y, color = team_name, fill = team_name), size = 2.5, shape = 21, alpha = 0.75) + 
  scale_color_manual(values = c(nbaColors$primary[6],nbaColors$primary[14], nbaColors$secondary[16]), aesthetics = "color", breaks = c("Cleveland Cavaliers", "Los Angeles Lakers", "Miami Heat"), labels = c("CLE", "LAL", "MIA")) + 
  scale_fill_manual(values = c(nbaColors$secondary[6], nbaColors$secondary[14], nbaColors$primary[16]), aesthetics = "fill", breaks = c("Cleveland Cavaliers", "Los Angeles Lakers", "Miami Heat"), labels = c("CLE", "LAL", "MIA")) + 
  ggtitle("LeBron James Career Points", subtitle = paste0("Career Points:"," ",cTotals$points[1], sep = "")) + 
  labs(fill = "Team Name", color = "Team Name") + 
  theme(plot.title = element_text(face = "bold", hjust = 0.5, color = nbaColors$primary[14], size = 22),
        plot.subtitle = element_text(hjust = 0.5, color = nbaColors$primary[14]),
        plot.caption = element_text(color = nbaColors$primary[14]),
        legend.title = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.text = element_text(hjust = 0.5, color = "black", vjust = 0.4),
        legend.background = element_rect(fill = "floralwhite"),
        legend.key.height= unit(2, 'cm'),
        strip.text = element_text(color = "white")) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc)) +
  geom_path(data = courtflip,
            aes(x = x, y = y, group = desc)) +
  geom_path(data = halfcourtLayout,
            aes(x = x, y = y, group = desc))

ggsave("lbjCareerPoints-team.pdf")
```

