---
title: "NBAtop10PPG-shotChart"
output: html_document
date: "2023-02-28"
---
#libraries
```{r setup, include=FALSE}
library(httr)
library(tidyverse)
library(jsonlite)
library(stringr)
library(nbastatR)
library(xml2)
library(rvest)
library(curl)
library(hexbin)
library(devtools)
library(prismatic)
library(extrafont)
library(cowplot)
```

#scrape function
```{r}
#NBA.com Scrape function
#####
#nba.com headers
headers = c(`Connection` = 'keep-alive',
            `Accept` = 'application/json, text/plain, */*',
            `x-nba-stats-token` = 'true',
            `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36',
            `x-nba-stats-origin` = 'stats',
            `Sec-Fetch-Site` = 'same-site',
            `Sec-Fetch-Mode` = 'cors',
            `Referer` = 'https://www.nba.com/',
            `Accept-Encoding` = 'gzip, deflate, br',
            `Accept-Language` = 'en-US,en;q=0.9')

#nba.com shot location scrape function
nbaTopScorersScrape <- function(season, playerIDNumber){
  url <- paste0("https://stats.nba.com/stats/shotchartdetail?AheadBehind=&CFID=33&CFPARAMS=",season,"&ClutchTime=&Conference=&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&Division=&EndPeriod=10&EndRange=28800&GROUP_ID=&GameEventID=&GameID=&GameSegment=&GroupID=&GroupMode=&GroupQuantity=5&LastNGames=0&LeagueID=00&Location=&Month=0&OnOff=&OppPlayerID=&OpponentTeamID=0&Outcome=&PORound=0&Period=0&PlayerID=",playerIDNumber,"&PlayerID1=&PlayerID2=&PlayerID3=&PlayerID4=&PlayerID5=&PlayerPosition=&PointDiff=&Position=&RangeType=0&RookieYear=&Season=",season,"&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StartPeriod=1&StartRange=0&StarterBench=&TeamID=0&VsConference=&VsDivision=&VsPlayerID1=&VsPlayerID2=&VsPlayerID3=&VsPlayerID4=&VsPlayerID5=&VsTeamID=", sep = "")
  
  res <- GET(url = url, add_headers(.headers=headers))
  
  json_resp <- fromJSON(content(res, "text"))
  
  frame <- data.frame(json_resp$resultSets$rowSet[1])
  colnames(frame) <- json_resp[["resultSets"]][["headers"]][[1]]
  
  Sys.sleep(3)
  
  frame <- frame %>%
    mutate(GAME_ID = as.numeric(GAME_ID),
           GAME_EVENT_ID = as.numeric(GAME_EVENT_ID),
           PLAYER_ID = as.numeric(PLAYER_ID),
           TEAM_ID = as.numeric(TEAM_ID),
           PERIOD = as.numeric(PERIOD),
           MINUTES_REMAINING = as.numeric(MINUTES_REMAINING),
           SECONDS_REMAINING = as.numeric(SECONDS_REMAINING),
           SHOT_DISTANCE = as.numeric(SHOT_DISTANCE),
           LOC_X = as.numeric(LOC_X),
           LOC_Y = as.numeric(LOC_Y),
           SHOT_ATTEMPTED_FLAG = as.numeric(SHOT_ATTEMPTED_FLAG),
           SHOT_MADE_FLAG = as.numeric(SHOT_MADE_FLAG),
           GAME_YEAR = as.numeric(substr(GAME_DATE, 1, 4)),
           GAME_MONTH = as.numeric(substr(GAME_DATE, 5, 6)),
           GAME_DAY = as.numeric(substr(GAME_DATE, 7, 8)))
  
  colnames(frame) <- tolower(colnames(frame))
  
  return(frame)
}

#league average scrape
lg_avg_scrape <- function(season, playerIDNumber){
  url <- paste0("https://stats.nba.com/stats/shotchartdetail?AheadBehind=&CFID=33&CFPARAMS=",season,"&ClutchTime=&Conference=&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&Division=&EndPeriod=10&EndRange=28800&GROUP_ID=&GameEventID=&GameID=&GameSegment=&GroupID=&GroupMode=&GroupQuantity=5&LastNGames=0&LeagueID=00&Location=&Month=0&OnOff=&OppPlayerID=&OpponentTeamID=0&Outcome=&PORound=0&Period=0&PlayerID=",playerIDNumber,"&PlayerID1=&PlayerID2=&PlayerID3=&PlayerID4=&PlayerID5=&PlayerPosition=&PointDiff=&Position=&RangeType=0&RookieYear=&Season=",season,"&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StartPeriod=1&StartRange=0&StarterBench=&TeamID=0&VsConference=&VsDivision=&VsPlayerID1=&VsPlayerID2=&VsPlayerID3=&VsPlayerID4=&VsPlayerID5=&VsTeamID=", sep = "")
  
  res <- GET(url = url, add_headers(.headers=headers))
  
  json_resp <- fromJSON(content(res, "text"))
  
  league_avg_data <- data.frame(json_resp$resultSets$rowSet[2])
  colnames(league_avg_data) <- json_resp[["resultSets"]][["headers"]][[2]]
  
  league_avg_data <- league_avg_data[,-1]
  colnames(league_avg_data) <- tolower(colnames(league_avg_data))
  colnames(league_avg_data) <- c("shot_zone_basic", "shot_zone_area", "shot_zone_range", "lg_avg_fga", "lg_avg_fgm", "lg_avg_fgPCT")
  
  league_avg_data <- league_avg_data %>%
    mutate(lg_avg_fga = as.numeric(as.character(lg_avg_fga)),
           lg_avg_fgm = as.numeric(as.character(lg_avg_fgm)),
           lg_avg_fgPCT = as.numeric(as.character(lg_avg_fgPCT)),
           shot_value = ifelse(shot_zone_basic %in% c("Above the Break 3", 
                                                      "Backcourt", 
                                                      "Left Corner 3", 
                                                      "Right Corner 3"), 3, 2))
  
  Sys.sleep(3)
  
  return(league_avg_data)
  }

```

#base setup (player/season selector)
```{r}
#set working directory
setwd("/Users/danielbrockett/Desktop/personalProject/TopScorers")

#nba.com player ID retrieval
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

#season inputs
sznStartYear <- c(2022)
sznEndYear <- sznStartYear + 1
years <- tibble(sznStartYear, sznEndYear)

#create season description
years <- years %>%
  mutate(sznYear = paste0(sznStartYear,"-",str_sub(sznEndYear, -2, -1), sep =""))

#bbRef player info
bbref <- bref_players_stats(sznEndYear[1], tables = "totals")
Sys.sleep(9)
rm(dataBREFPlayerTotals)

#clean cols
keep2 <- c(1:20, 26:43)
bbref <- bbref[,keep2]

#bbRef player ids
playerIDs <- bbref %>%
  mutate(ppg = ptsTotals/countGames) %>%
  arrange(desc(ppg)) %>%
  head(10) %>%
  select(slugPlayerBREF, idPlayerNBA)

#rename columns
colnames(playerIDs) <- c("playerSlug", "nbaPlayerID")
```


#data collection
```{r}
#nba.com scrape (Field Goal Shot Locations)
gameEvents <- tibble()

#for loop to collect data (NBA.com)
for (i in 1:nrow(playerIDs)){
  events <- nbaTopScorersScrape(years$sznYear, playerIDs[i,]$nbaPlayerID)
  
  gameEvents <- events %>% bind_rows(gameEvents)
  
  Sys.sleep(7)
}


#league average scrape
#nba.com scrape (Field Goal Shot Locations)
lg_avgs <- tibble()

#for loop to collect data (NBA.com)
for (i in 1:nrow(years)){
  avgs <- lg_avg_scrape(years[i,]$sznYear, playerIDs[1,]$nbaPlayerID)
  
  lg_avgs <- avgs %>% bind_rows(lg_avgs)
  
  Sys.sleep(7)
}

#FGM check
gameEvents %>%
  group_by(player_id, player_name) %>%
  summarise(shotsMade = sum(shot_made_flag)) %>%
  arrange(desc(shotsMade))
```

#save data
```{r}
#save data (NBA.com)
write_csv(gameEvents, "topScorersFGA.csv")
write_csv(lg_avgs, "NBAAverages.csv")

```

#load data
```{r}
#field goals
gameEvents <- read_csv("topScorersFGA.csv")
lg_avgs <- read_csv("NBAAverages.csv")
```

#NBA court dimensions
```{r}
#circle function
circle_points <- function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

#nba court dimensions
width <- 50
height <- 94
key_height <- 19
inner_key_width <- 12
outer_key_width <- 16
backboard_width <- 6
backboard_offset <- 4
neck_length <- 0.5
hoop_radius <- 0.75
hoop_center_y <- backboard_offset + neck_length + hoop_radius
three_point_radius <- 23.75
three_point_side_radius <- 22
three_point_side_height <- 14
inner_tip_off_radius <- 2
outer_tip_off_radius <- 6
```


#Shot Location Cleaning
```{r}
#re-name to save original data (easy reset point)
nbaShots <- gameEvents

#modify shot location distances
nbaShots <- nbaShots %>% 
  mutate(loc_x = loc_x / 10, loc_y = loc_y / 10 + hoop_center_y)

#remove fourth column ("shot chart detail" column)
nbaShots <- nbaShots[,-1]

#cleaning up dataframe
unique(nbaShots$shot_type)

nbaShots$game_date <- paste0(nbaShots$game_year,"-", nbaShots$game_month,"-", nbaShots$game_day, sep ="")
nbaShots$game_date <- ymd(nbaShots$game_date)

nbaShots <- nbaShots %>%
  mutate(shot_value = ifelse(str_detect(shot_type, "3PT"), 3, ifelse(str_detect(shot_type, "2PT"), 2, NA)), pointsScored = shot_value * shot_made_flag)
```


#court themes
```{r}
#court themes
court_themes <- list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20")
)
```

#court graphing function
```{r}
#court creation function
graph_court <- function(court_theme) {
  
  court_points <- tibble(x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
                             y = c(height, 0, 0, height, height),
                             desc = "perimeter")
  
  court_points <- bind_rows(court_points, tibble(x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
                                                 y = c(0, key_height, key_height, 0),
                                                 desc = "outer_key"))
  
  court_points <- bind_rows(court_points , tibble(x = c(-backboard_width / 2, backboard_width / 2),
                                                  y = c(backboard_offset, backboard_offset),
                                                  desc = "backboard"))
  
  court_points <- bind_rows(court_points , tibble(x = c(0, 0),
                                                  y = c(backboard_offset, backboard_offset + neck_length),
                                                  desc = "neck"))
  
  foul_circle <- circle_points(center = c(0, key_height),
                               radius = inner_key_width / 2)
  
  foul_circle_top <- filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom <- filter(foul_circle, y < key_height) %>%
    mutate(angle = atan((y - key_height) / x) * 180 / pi,
           angle_group = floor((angle - 5.625) / 11.25),
           desc = paste0("foul_circle_bottom_", angle_group)) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop <- circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted <- circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle <- circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line <- tibble(x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
                            y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
                            desc = "three_point_line")
  
  courtLayout <- bind_rows(court_points,
                            foul_circle_top,
                            foul_circle_bottom,
                            hoop,
                            restricted,
                            three_point_line)
  courtflip <- courtLayout
  courtflip$y <- (-courtLayout$y) + 94

  innerTipOffCircle <- circle_points(center = c(0, height/2), radius = inner_tip_off_radius) %>%
    mutate(desc = "innerTipOffCircle")
  outerTipOffCircle <- circle_points(center = c(0, height/2), radius = outer_tip_off_radius) %>%
    mutate(desc = "outerTipOffCircle")
  
  halfcourt_line <- tibble(x = c(width / 2, -width / 2),
                             y = c(height / 2, height / 2),
                             desc = "halfcourtLine")
  halfcourtLayout <- rbind(innerTipOffCircle,
                           outerTipOffCircle,
                           halfcourt_line)

#plotting court
  ggplot() +
    geom_path(data = courtLayout,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) +
    geom_path(data = courtflip,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) + 
    geom_path(data = halfcourtLayout,
              aes(x = x, y = y, group = desc),
              color = court_theme$lines) +
    coord_fixed(ylim = c(0, 94), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(text = element_text(color = court_theme$text),
          plot.background = element_rect(fill = 'gray20', color = 'gray20'),
          panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.text = element_blank(),
          axis.title = element_blank(),
          axis.ticks = element_blank(),
          legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
          legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
          legend.position = "bottom",
          legend.key = element_blank(),
          legend.text = element_text(size = rel(1.0)))
  }
```

#hexbins
```{r}
hex_bounds <- function(x, binwidth) {
  c(plyr::round_any(min(x), binwidth, floor),
    plyr::round_any(max(x), binwidth, ceiling))
}

calculate_hex_coords <- function(shots, binwidths) {
  xbnds = hex_bounds(nbaShots$loc_x, binwidths[1])
  xbins = diff(xbnds) / binwidths[1]
  ybnds = hex_bounds(nbaShots$loc_y, binwidths[2])
  ybins = diff(ybnds) / binwidths[2]
  
  hb <- hexbin(x = nbaShots$loc_x,
               y = nbaShots$loc_y,
               xbins = xbins,
               xbnds = xbnds,
               ybnds = ybnds,
               shape = ybins / xbins,
               IDs = TRUE)
  
  shots <- nbaShots %>%
    mutate(hexbin_id = hb@cID)
  
  hexbin_stats <- shots %>%
    group_by(player_id, player_name, hexbin_id) %>%
    summarize(hex_attempts = n(),
              hex_pct = mean(shot_made_flag),
              hex_points_scored = sum(shot_made_flag * shot_value),
              hex_points_per_shot = mean(shot_made_flag * shot_value)) 
  
  hexbin_ids_to_zones <- shots %>%
    group_by(player_id, player_name, hexbin_id, shot_zone_range, shot_zone_area) %>%
    summarize(attempts = n()) %>%
    ungroup() %>%
    arrange(hexbin_id, desc(attempts)) %>%
    group_by(hexbin_id) %>%
    select(player_id, player_name, hexbin_id, shot_zone_range, shot_zone_area)
  
  hexbin_stats <- inner_join(hexbin_stats, hexbin_ids_to_zones, by = c("player_id", "player_name", "hexbin_id"))
  
  # from hexbin package, see: https://github.com/edzer/hexbin
  sx = hb@xbins / diff(hb@xbnds)
  sy = (hb@xbins * hb@shape) / diff(hb@ybnds)
  dx = 1 / (2 * sx)
  dy = 1 / (2 * sqrt(3) * sy)
  origin_coords <- hexcoords(dx, dy)
  
  hex_centers <- hcell2xy(hb)
  
  hexbin_coords <- bind_rows(lapply(1:hb@ncells, function(i) {
    data.frame(x = origin_coords$x + hex_centers$x[i],
               y = origin_coords$y + hex_centers$y[i],
               center_x = hex_centers$x[i],
               center_y = hex_centers$y[i],
               hexbin_id = hb@cell[i]
    )
  }))
  
  hexbin_coords <- inner_join(hexbin_coords, hexbin_stats, by = "hexbin_id")
  return(hexbin_coords)
}

calculate_hexbins_from_shots <- function(shots, league_averages, binwidths, min_radius_factor) {
  if (nrow(shots) == 0) {
    return(list())
  }
  
  zone_stats <- shots %>%
    group_by(player_id, player_name, shot_zone_range, shot_zone_area) %>%
    summarize(zone_attempts = n(),
              zone_pct = mean(shot_made_flag),
              zone_pts_scored = sum(shot_made_flag * shot_value),
              zone_pts_per_shot = mean(shot_made_flag * shot_value))
  
  league_zone_stats <- lg_avgs %>%
    group_by(shot_zone_range, shot_zone_area) %>%
    summarize(league_attempts = sum(lg_avg_fga),
              league_pct = sum(lg_avg_fgm) / sum(lg_avg_fga),
              league_pts_scored = sum(lg_avg_fgm * shot_value),
              league_pts_per_shot = mean(lg_avg_fgm * shot_value)
              )
  
  hex_data <- calculate_hex_coords(shots, binwidths = binwidths)
  
  join_keys <- c("shot_zone_area", "shot_zone_range")
  
  hex_data <- hex_data %>%
    inner_join(zone_stats, by = c("player_id", "player_name", "shot_zone_area", "shot_zone_range")) %>%
    inner_join(league_zone_stats, by = join_keys)
  
  max_hex_attempts <- max(hex_data$hex_attempts)
  
  
  hex_data <- hex_data %>%
    mutate(radius_factor = min_radius_factor + (1 - min_radius_factor) * log((hex_attempts^1.3) + 1) / log((max_hex_attempts) + 1),
           adj_x = center_x + radius_factor * (x - center_x),
           adj_y = center_y + radius_factor * (y - center_y),
           fg_diff_pct = pmin(pmax((zone_pct - league_pct))),
           bounded_fg_pct = pmin(pmax(zone_pct)),
           bounded_pts_per_shot = pmin(pmax(zone_pts_per_shot)))
  
  hex_data <- hex_data %>%
    mutate(center_x = ifelse(center_x >= 25, 25, center_x),
           center_x = ifelse(center_x <= -25, -25, center_x))
  
  return(hex_data)
}

hd <- calculate_hexbins_from_shots(nbaShots, league_averages , binwidths = c(1.5, 1.5), min_radius_factor = 0.8)  

```


#hexbin graphing info
```{r}
hexStats <- hd %>%
  group_by(player_name) %>%
  summarise(worst_fg_diff = min(fg_diff_pct),
            best_fg_diff = max(fg_diff_pct)) %>%
  arrange(desc(best_fg_diff), desc(worst_fg_diff))

fg_limit_min <- -round(max(hexStats$best_fg_diff), 2) - 0.01
fg_limit_max <- round(max(hexStats$best_fg_diff), 2) + 0.01

fg_bin_width <- round((fg_limit_max * 2) / 9, 2)

shotPCT_number <- c(fg_limit_min,
                    0 - (fg_bin_width*4),
                    0 - (fg_bin_width*3),
                    0 - (fg_bin_width*2),
                    0 - (fg_bin_width),
                    0,
                    0 + (fg_bin_width),
                    0 + (fg_bin_width*2),
                    0 + (fg_bin_width*3),
                    0 + (fg_bin_width*4),
                    fg_limit_max)

shot_pct_breaks <- tibble(shotPCT_number)

shot_pct_breaks <- shot_pct_breaks %>%
  mutate(pct_shot = shotPCT_number*100,
         sp = paste0(pct_shot,"%", sep = ""))

playerInfo <- bbref %>%
  mutate(ppg = round((ptsTotals/countGames), 2)) %>%
  arrange(desc(ppg)) %>%
  head(10) %>%
  select(namePlayer, idPlayerNBA, slugSeason, ppg)

colnames(playerInfo) <- c("player_name", "player_id", "slugSeason", "ppg")

hd <- left_join(x = hd, y = playerInfo, by = c("player_name", "player_id"))

hd <- hd %>%
  group_by(hexbin_id) %>%
  mutate(playerLabel = paste0(ppg," Pts/G", " - ", player_name, sep = ""))
```

#graphing hexbin data
```{r}
adj <- graph_court(court_themes$light) +
  geom_polygon(data = hd, 
               aes(x = adj_x, y = adj_y, group = hexbin_id, fill = fg_diff_pct),
               alpha = 2,
               color = "black",
               linewidth = 0.15) +
  scale_fill_distiller(direction = -1, 
                       palette = "RdBu", 
                       limits = c(fg_limit_min, 
                                  fg_limit_max), 
                       breaks = shot_pct_breaks$shotPCT_number,
                       labels = shot_pct_breaks$sp,
                       "FG Percentage Points vs. League Average") +
facet_wrap(~playerLabel, nrow = 2, as.table = FALSE) +
  guides(fill=guide_legend(label.position = 'bottom',
                           title.position = 'top',
                           title.hjust = .5,
                           title.vjust = 0,
                           label.vjust = 1,
                           nrow = 1)) +
  theme(text=element_text(size=14),
        legend.spacing.x = unit(4, "pt"),
        legend.text = element_text(hjust = 10),
        legend.title=element_text(size=14),
        legend.title.align = 0.5,
        legend.box.just = "center",
        legend.margin=margin(0,5,-1,5),
        legend.box.margin=margin(-20,0,5,0),
        strip.text.x = element_text(hjust = 0.5,
                                    size = 12,
                                    color = "black"),
        strip.background=element_rect(colour="black",
                                      fill="floralwhite"),
        plot.margin = margin(.2,.3,-.1,.15, "cm"),
        plot.title = element_text(hjust = 0.5,
                                  vjust = 1, 
                                  size = 20,
                                  face = "bold",
                                  color = "floralwhite"),
        plot.subtitle = element_text(hjust = 0.5,
                                     vjust = 1,
                                     size = 14,
                                     color = "floralwhite"),
        plot.caption = element_text(size = 10,
                                    hjust = 1.005,
                                    vjust = 5,
                                    color = "floralwhite")) +
  ggtitle("NBA Points Per Game Leaders",
          subtitle = "2022-23 Regular Season") +
  labs(caption = "*As of 2/27")

adj
#ggsave("NBAppgLeaders-adjustedXY.pdf")
```
